name: cypress-helloworld-tryout

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: helloworld
        run: |
          cd cypress-helloworld-tryout
            npm run into_cy_chrome
          cd ..
