name: cypress-mochawesome-reporter-tryout

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: helloworld
        run: |
          cd cypress-mochawesome-reporter-tryout
            npm i
            npx cypress run
          cd ..
      - uses: actions/upload-artifact@v2 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: cypress-mochawesome-reporter-tryout/mochawesome-report/mochawesome.json

      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # artifact name
          name: JEST Tests # Name of the check run which will be created
          path: 'cypress-mochawesome-reporter-tryout/mochawesome-report/mochawesome.json' # Path to test results (inside artifact .zip)
          reporter: mocha-json # Format of test results
