name: cypress-mochawesome-reporter-tryout

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: helloworld
        run: |
          cd cypress-mochawesome-reporter-tryout
            npm i
            npx cypress run
          cd ..
      - uses: actions/upload-artifact@v2 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: cypress-mochawesome-reporter-tryout/mochawesome-report/mochawesome.json
