name: docker-cypress-v10-tryout

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test docker
        run: |
          cd docker-cypress-v10-tryout
            npm run docker_run
          cd ..
