name: 'merge-to-master'

on:
  workflow_run:
    workflows:
      - docker_cypress-docker-v10-tryout
      - docker_included-with-plugins-xpath-tryout
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: wait success
        uses: ahmadnassri/action-workflow-run-wait@v1

      - name: checkout
        uses: actions/checkout@v3

      - name: merge
        if: ${{ !startsWith(github.ref, 'refs/heads/test/') }}
        run: |
          cd github-js-build-merger-tryout
            npm i
            node ./merge_to_master.js
          cd ..
