name: 'Test Report'
on:
  workflow_run:
    workflows: ['cypress-mochawesome-reporter-tryout'] # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: phoenix-actions/test-reporting@v8
        with:
          artifact: test-results # artifact name
          name: JEST Tests # Name of the check run which will be created
          path: '*.json' # Path to test results (inside artifact .zip)
          reporter: mocha-json # Format of test results
