name: 'Test Report'

on:
  workflow_run:
    workflows: ['cypress-mochawesome-helloworld-tryout', 'cypress-helloworld-tryout'] # runs after CI workflow
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: ping-dead-man-timer
        run: |
          curl -fsS -m 10 --retry 5 http://healthcheck.iamon99.com/ping/767db2f9-0846-4de1-a3c1-3b5796130bdf
